export const servicesData =  {
    categories: ['All', 'Clothing', 'Accessories'],
    services: [
        { id: 1, image: '/img/Services/service-1.jpg', title: 'Blue hoodie', category: 'Clothing', description: 'A must-have in the spring and fall season. This hoodie will keep you warm.', cost: 39.90 },
        { id: 2, image: '/img/Services/service-2.jpg', title: 'Orange hoodie', category: 'Clothing', description: 'A must-have in the spring and fall season. This hoodie will keep you warm.', cost: 39.90 },
        { id: 3, image: '/img/Services/service-3.jpg', title: 'Pink hoodie', category: 'Clothing', description: 'A must-have in the spring and fall season. This hoodie will keep you warm.', cost: 39.90 },
        { id: 4, image: '/img/Services/service-4.jpg', title: 'Blue hoodie', category: 'Clothing', description: 'A must-have in the spring and fall season. This hoodie will keep you warm.', cost: 39.90 },
        { id: 5, image: '/img/Services/service-5.jpg', title: 'Orange hoodie', category: 'Clothing', description: 'A must-have in the spring and fall season. This hoodie will keep you warm.', cost: 39.90 },
        { id: 6, image: '/img/Services/service-6.jpg', title: 'Pink hoodie', category: 'Clothing', description: 'A must-have in the spring and fall season. This hoodie will keep you warm.', cost: 39.90 },
        { id: 7, image: '/img/Services/service-7.jpg', title: 'T-Shirt with illustration', category: 'Clothing', description: 'Just a beautiful simple T-shirt with our unique illustration that shows the importance of peer support and love.', cost: 19.90 },
        { id: 8, image: '/img/Services/service-8.jpg', title: 'T-Shirt blue', category: 'Clothing', description: 'A nice shirt with a bright teenline logo.', cost: 19.90 },
        { id: 9, image: '/img/Services/service-9.jpg', title: 'White T-Shirt with logo', category: 'Clothing', description: 'A nice shirt with a bright teenline logo.', cost: 19.90 },
        { id: 10, image: '/img/Services/service-10.jpg', title: 'Hat with logo', category: 'Accessories', description: 'This will save you from sunburn, bad-hair days and let your friend know about Teenline.', cost: 14.90 },
        { id: 11, image: '/img/Services/service-11.jpg', title: 'Tote Bag with illustration', category: 'Accessories', description: 'Just a beautiful simple tote bag with our unique illustration that shows the importance of peer support and love.', cost: 19.90 },
        { id: 12, image: '/img/Services/service-12.jpg', title: 'Pink Pin with illustration', category: 'Accessories', description: 'Get one on your backpack to help the teenline community to grow in your school.', cost: 6.00 },
        { id: 13, image: '/img/Services/service-13.jpg', title: 'Blue Pin with illustration', category: 'Accessories', description: 'Get one on your backpack to help the teenline community to grow in your school.', cost: 6.00 },
        { id: 14, image: '/img/Services/service-14.jpg', title: 'iPhone 12 case', category: 'Accessories', description: 'Get the phone case and let it serve as a reminder to reach to others who might need help', cost: 19.90 },
        { id: 15, image: '/img/Services/service-15.jpg', title: 'Ballon with illustration', category: 'Accessories', description: 'Leftover ballons from our special events, grab one to hold unto the special memories you made at our event.', cost: 2.00 },
        { id: 16, image: '/img/Services/service-16.jpg', title: 'Ballon with logo', category: 'Accessories', description: 'Leftover ballons from our special events, grab one to hold unto the special memories you made at our event.', cost: 2.00 },
    ],
}
